language: ruby
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: ruby-head
dist: trusty
