#!/usr/bin/env ruby
require 'rubygems'
$:.unshift(File.expand_path(File.join(File.dirname(__FILE__), "..", 'lib')))
require "bundler/setup"
require 'logger'
require 'rdf'
require 'rdf/turtle'
begin
  require 'linkeddata'
rescue LoadError
  %w(rdf/rdfa rdf/rdfxml rdf/vocab rdf/xsd).each do |gem|
    begin
      require gem
    rescue LoadError
    end
  end
end
require 'rdf/ntriples'
require 'ebnf/ll1/parser'
require 'getoptlong'

def run(input, **options)
  if options[:profile]
    require 'profiler'
  end

  reader_class = RDF::Reader.for(options[:input_format].to_sym)
  raise "Reader not found for #{options[:input_format]}" unless reader_class

  start = Time.new
  num = 0
  Profiler__::start_profile if options[:profile]
  if options[:output_format] == :ntriples || options[:quiet] || options[:benchmark]
    r = reader_class.new(input, **options[:parser_options])
    r.each do |statement|
      num += 1
      if options[:errors] && statement.invalid?
        $stderr.puts "Invalid statement at #{r.lineno}: #{statement.inspect}"
      elsif options[:benchmark]
        # Don't do anything
      elsif options[:quiet]
        print "." if options[:quiet] == 1
      else
       options[:output].puts statement.to_ntriples
      end
    end
  elsif options[:output_format] == :inspect
    reader_class.new(input, **options[:parser_options]).each do |statement|
      num += 1
      options[:output].puts statement.inspect
    end
  else
    r = reader_class.new(input, **options[:parser_options])
    g = RDF::Repository.new << r
    num = g.count
    options[:output].puts g.dump(options[:output_format], prefixes:  r.prefixes, **options[:writer_options])
  end
  if options[:profile]
    Profiler__::stop_profile
    Profiler__::print_profile($stderr)
  end
  secs = Time.new - start
  $stderr.puts "Parsed #{num} statements in #{secs} seconds @ #{num/secs} statements/second."
rescue Exception => e
  fname = input.respond_to?(:path) ? input.path : "-stdin-"
  $stderr.puts("Error in #{fname}: #{e.message}")
  $stderr.puts "Backtrace: " + e.backtrace.join("\n  ")
  raise e
end

logger = Logger.new(STDERR)
logger.level = Logger::WARN
logger.formatter = lambda {|severity, datetime, progname, msg| "%5s %s\n" % [severity, msg]}

parser_options = {
  base_uri:  nil,
  validate:  false,
  logger: logger,
}

writer_options = {
  base_uri:  nil,
  standard_prefixes:  true,
  logger: logger,
}

options = {
  parser_options:  parser_options,
  writer_options:  writer_options,
  output:  STDOUT,
  output_format:  :ntriples,
  input_format:  :ttl,
}
input = nil

OPT_ARGS = [
  ["--benchmark", GetoptLong::NO_ARGUMENT, "Just parse, do not process output"],
  ["--canonicalize", GetoptLong::NO_ARGUMENT, "Canonize all terms"],
  ["--data", GetoptLong::NO_ARGUMENT, "Remove all except plain RDF triples (formulae, forAll, etc)v"],
  ["--debug", GetoptLong::NO_ARGUMENT, "Debugging output"],
  ["--errors", GetoptLong::NO_ARGUMENT, "Display invalid statements"],
  ["--execute", "-e", GetoptLong::REQUIRED_ARGUMENT, "Run against source in argument"],
  ["--format", GetoptLong::REQUIRED_ARGUMENT, "Output format, any RDF format symbol, sxp, or inspect"],
  ["--freebase", GetoptLong::NO_ARGUMENT, "Use Freebase reader (obsolete)"],
  ["--help", "-?", GetoptLong::NO_ARGUMENT, "print this message"],
  ["--input-format", GetoptLong::REQUIRED_ARGUMENT, "Format of the input file, defaults to ttl"],
  ["--info", GetoptLong::NO_ARGUMENT, "Show progress on execution"],
  ["--output", "-o", GetoptLong::REQUIRED_ARGUMENT, "Save output to file"],
  ["--profile", GetoptLong::NO_ARGUMENT, "Show an execution profile"],
  ["--quiet", GetoptLong::NO_ARGUMENT, "Do not show parser output"],
  ["--rdfstar", GetoptLong::NO_ARGUMENT, "Parse as RDF-star"],
  ["--stream", GetoptLong::NO_ARGUMENT, "Use streaming writer"],
  ["--uri", GetoptLong::REQUIRED_ARGUMENT, "Default base URI"],
  ["--validate", GetoptLong::NO_ARGUMENT, "Run parser in strict validation mode"],
  ["--verbose", GetoptLong::NO_ARGUMENT, "Verbose output"],
]

def usage
  STDERR.puts %{
    RDF::Turtle version #{RDF::Turtle::VERSION}
    
    Usage: #{$0} [options] file ...
  }.gsub(/^    /, '')
  width = OPT_ARGS.map do |o|
    l = o.first.length
    l += o[1].length + 2 if o[1].is_a?(String)
    l
  end.max
  OPT_ARGS.each do |o|
    s = "  %-*s  " % [width, (o[1].is_a?(String) ? "#{o[0,2].join(', ')}" : o[0])]
    s += o.last
    STDERR.puts s
  end
  exit(1)
end

opts = GetoptLong.new(*OPT_ARGS.map {|o| o[0..-2]})

opts.each do |opt, arg|
  case opt
  when '--debug'        then logger.level = Logger::DEBUG
  when '--uri'          then parser_options[:base_uri] = writer_options[:base_uri] = arg
  when '--benchmark'    then options[:benchmark] = true
  when '--canonicalize' then parser_options[:canonicalize] = true
  when '--errors'       then options[:errors] = true
  when '--execute'      then input = arg
  when '--format'       then options[:output_format] = arg.to_sym
  when '--freebase'     then parser_options[:freebase] = true
  when "--help"         then usage()
  when '--info'         then logger.level = Logger::INFO
  when '--input-format' then options[:input_format] = arg.to_sym
  when '--output'       then options[:output] = File.open(arg, "w")
  when '--profile'      then options[:profile] = true
  when '--rdfstar'      then parser_options[:rdfstar] = true
  when '--quiet'
    options[:quiet] = options[:quiet].to_i + 1
    logger.level = Logger::FATAL
  when '--stream'       then writer_options[:stream] = true
  when '--validate'     then parser_options[:validate] = true
  when '--verbose'      then $verbose = true
  end
end

if ARGV.empty?
  s = input ? input : $stdin.read
  run(StringIO.new(s), **options)
else
  ARGV.each do |test_file|
    run(Kernel.open(test_file), **options)
  end
end
puts
